### ISSUE TITLE
プロジェクトに不要なレイヤが含まれている

### ISSUE THREAD

**Issue by wata909** [amx-project/f#2]
./00.fgb|layername=merged　というレイヤがプロジェクトに含まれているようです。削除したほうがいいと思います

**Comment by wata909** [comment]
[f.zip](https://github.com/amx-project/f/files/12328403/f.zip)
削除したqgzをzipにしてアップしました。

**Comment by hfu** [comment]
ありがとうございます。下記のコミットで反映しました。
（その他、スタイルの調整なども合わせて反映しています。）

https://github.com/amx-project/f/commit/bb3d4e3bf7a4148de7a39c06dc38eeae337cab8f#diff-cdf82b9d75bc79a981c0a656c1ca44881cee6a362cbccc4c9b5808db2d571a6c

**Comment by wata909** [comment]
ありがとうございます。修正、確認しました！
